# -*- coding: utf-8 -*-
"""Project_Bangkit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0ICTH3hVFMIeYM-javjldUjq37uJwuD
"""

import string
import numpy as np

#Name of user
def user_name():
  name = input("How do I call you Mr/Mrs? ")
  return name

#User gender
def user_gender(name):
  gender = input("Select your gender " + name + "\nMale/Female ").lower()
  while gender not in ['male', 'female']:
    print("Please insert your gender correctly")
    gender = input("Select your gender " + name + "\nMale/Female ").lower()
  return gender

# input_data
def list_activity(weight):
  a = list(range(1, 118))
  for i in range(0, len(a)):
    a[i] = str(a[i])

  print("""
  (1) Cycling
  (2) Stationary Cycling
  (3) Calisthenics
  (4) Circuit training, minimal rest
  (5) Weight lifting
  (6) Health club exercise
  (7) Stair Machine
  (8) Rowing Machine
  (9) Ski machine
  (10) Aerobics
  (11) Water Aerobics
  (12) Jazzercise
  (13) Stretching
  (14) Ballet, twist, jazz, tap
  (15) Ballroom dancing 
  (16) Running
  (17) Track and field
  (18) Archery
  (19) Badminton
  (20) Basketball
  (21) Billiards
  (22 )Bowling
  (23) Boxing
  (24) Coaching: football, basketball, soccer
  (25) Cricket
  (26) Croquet
  (27) Curling
  (28) Darts (wall or lawn)
  (29) Fencing
  (30) Football
  (31) Frisbee
  (32) Golf
  (33) Gymnastics
  (34) Hacky sack
  (35) Handball
  (36) Hockey (field or ice hockey)
  (37) Riding a horse
  (38) Jai alai
  (39) Martial arts
  (40) Krav maga training
  (41) Juggling
  (42) Kickball
  (43) Lacrosse
  (44) Orienteering
  (45) Paddleball
  (46) Polo
  (47) Racquetball
  (48) Rock climbing
  (49) Jumping rope
  (50) Rugby
  (51) Shuffleboard, lawn bowling
  (52) Skateboarding
  (53) Roller skating
  (54) Roller blading, in-line skating
  (55) Sky diving
  (56) Soccer
  (57) Baseball
  (58) Softball
  (59) Squash
  (60) Table tennis, ping pong
  (61) Tai chi
  (62) Tennis
  (63) Trampoline
  (64) Volleyball
  (65) Wrestling
  (66) Wallyball
  (67) Backpacking, hiking with pack
  (68) Carrying infant
  (69) Playing with children
  (70) Loading, unloading car
  (71) Climbing hills
  (72) Bird watching
  (73) Marching, rapidly, military
  (74) Children's game, hopscocth, dodgeball
  (75) Pushing stroller or walking with children
  (76) Pushing a wheelchair
  (77) Race walking
  (78) Rock climbing, mountain climbing
  (79) Walking
  (80) Boating, power, speed boat
  (81) Canoeing
  (82) Crew, sculling, rowing
  (83) Kayaking
  (84) Paddle boat
  (85) Windsurfing
  (86) Sailing
  (87) Skiing
  (88) Skin diving
  (89) Snorkeling
  (90) Surfing, body surfing or board surfing
  (91) Whitewater rafting
  (92) Swimming
  (93) Water aerobics
  (94) Water polo
  (95) Water volleyball
  (96) Water jogging
  (97) Diving, springboard or platform
  (98) Ice skating
  (99) Cross country snow skiing
  (100) Downhill snow skiing
  (101) Sledding, tobagganing, luge
  (102) Snow shoeing
  (103) Snowmobiling
  (104) General Housework
  (105) Cleaning gutters
  (106) Painting
  (107) Playing with animal
  (108) Mowing lawn
  (109) Snow blower
  (110) Shoveling snow by hand
  (111) Raking lawn
  (112) Gardening
  (113) Carpentry
  (114) Carrying loads
  (115) Cleaning
  (116) Walking, pushing a wheelchair
  (117) Teach physical education, exercise class
"""
)

  activity = input("Select your today activities ")
  if activity == "1":
    print("""
    (a) <4.5 m/s, leisure bicycling
    (b) 4.5 - 5.4 m/s, light
    (c) 5.4 - 6.2 m/s, moderate
    (d) 6.2 - 7.1 m/s, vigorous
    (e) 7.1 - 8.5 m/s, very fast, racing
    (f) >9 m/s, racing
    (g) Mountain bike, bmx
    (h) Unicycling
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:8]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration) 
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration) 
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.38)*duration) 
    elif kind == "f":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((16*weight-0.64)*duration)
    elif kind == "g":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8.5*weight+0.62)*duration)
    elif kind == "h":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.36)*duration)


  elif activity == "2":
    print("""
      (a) very light
      (b) light
      (c) moderate
      (d) vigorous
      (e) very vigorous
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:5]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5.5*weight+0.83)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.94)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10.5*weight+1.2)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12.5*weight+1.36)*duration)


  elif activity == "3":
    print("""
    (a) light
    (b) vigorous, pushups, situps
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight-0.26)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)


  elif activity == "4":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)


  elif activity == "5":
    print("""
    (a) light workout
    (b) body building, vigorous
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)


  elif activity == "6":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5.5*weight+0.84)*duration)


  elif activity == "7":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((9*weight-1.15)*duration)


  elif activity == "8":
    print("""
    (a) light
    (b) moderate
    (c) vigorous
    (d) very vigorous
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight+0.26)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.94)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8.5*weight+0.62)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.38)*duration)


  elif activity == "9":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.94)*duration)


  elif activity == "10":
    print("""
    (a) low impact
    (b) general
    (c) high impact
    (d) step aerobics
    (e) instructing aerobic class
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:5]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.36)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6.5*weight+0.45)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.94)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8.5*weight+0.62)*duration)  
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration) 

  elif activity == "11":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)


  elif activity == "12":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6*weight+0.4)*duration)


  elif activity == "13":
    print("""
    (a) mild
    (b) hatha yoga
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)


  elif activity == "14":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.8)*duration)


  elif activity == "15":
    print("""
    (a) slow
    (b) fast
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5.5*weight+0.84)*duration)


  elif activity == "16":
    print("""
    (a) 8 km/h, general
    (b) 8.5 km/h, cross country
    (c) 9.5 km/h, on a track, team practice
    (d) 10.5 km/h
    (e) 11 km/h
    (f) 12 km/h
    (g) 13 km/h
    (h) 14 km/h
    (i) 14.5 km/h, stairs, up
    (j) 16 km/h
    (k) 17.5 km/h
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:11]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.16)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((11*weight-1)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((11.5*weight+0.82)*duration)
    elif kind == "f":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12.5*weight+1.35)*duration)
    elif kind == "g":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((13.5*weight+1.4)*duration)
    elif kind == "h":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((14*weight-0.8)*duration)
    elif kind == "i":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((15*weight-0.25)*duration)
    elif kind == "j":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((16*weight-0.65)*duration)
    elif kind == "k":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((18*weight)*duration)


  elif activity == "17":
    print("""
    (a) shot, discus
    (b) high jump, pole vault
    (c) hurdles
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)


  elif activity == "18":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3.5*weight+0.25)*duration)
  elif activity == "19":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4.5*weight+0.75)*duration)


  elif activity == "20":
    print("""
    (a) shooting basket
    (b) non game
    (c) wheelchair
    (d) officiating
    (e) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:5]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4.5*weight+0.75)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6.5*weight+0.45)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
  
  
  elif activity == "21":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)  
  elif activity == "22":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)  


  elif activity == "23":
    print("""
    (a) punching bag
    (b) sparring
    (c) in ring
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.15)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.375)*duration)


  elif activity == "24":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)  
  elif activity == "25":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)  
  elif activity == "26":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)  
  elif activity == "27":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)  
  elif activity == "28":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)  
  elif activity == "29":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6*weight+0.4)*duration)  


  elif activity == "30":
    print("""
    (a) playing catch
    (b) touch, flag, general
    (c) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.5)*duration)


  elif activity == "31":
    print("""
    (a) general
    (b) ultimate frisbee
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)


  elif activity == "32":
    print("""
    (a) driving range, miniature golf 
    (b) using power cart
    (c) walking and pulling clubs
    (d) general, walking and carrying clubs
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight+0.25)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4.28*weight+1.4)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4.5*weight+0.75)*duration)


  elif activity == "33":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)


  elif activity == "34":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)


  elif activity == "35":
    print("""
    (a) team 
    (b) general
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.375)*duration)


  elif activity == "36":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((12*weight-1.375)*duration)


  elif activity == "37":
    print("""
    (a) riding, walking
    (b) horseshoe pitching
    (c) saddling horse, grooming horse
    (d) general
    (e) moderate
    (f) trotting
    (g) galloping
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:7]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight+0.25)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "f":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6.5*weight+0.45)*duration)
    elif kind == "g":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)


  elif activity == "38":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((12*weight-1.375)*duration)

  elif activity == "39":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((10*weight+0.62)*duration)


  elif activity == "40":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "41":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.95)*duration)
  elif activity == "42":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)
  elif activity == "43":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((9*weight-1.15)*duration)
  elif activity == "44":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((10*weight+0.62)*duration)


  elif activity == "45":
    print("""
    (a) general
    (b) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
  
  elif activity == "46":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)

  elif activity == "47":
    print("""
    (a) general
    (b) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)

  elif activity == "48":
    print("""
    (a) rappelling
    (b) ascending rock
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((11*weight-1)*duration)

  elif activity == "49":
    print("""
    (a) slow
    (b) moderate
    (c) fast
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.375)*duration)

  elif activity == "50":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((10*weight-0.62)*duration)
  elif activity == "51":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)
  elif activity == "52":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)
  elif activity == "53":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.95)*duration)
  elif activity == "54":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((12*weight-1.375)*duration)
  elif activity == "55":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)

  elif activity == "56":
    print("""
    (a) general
    (b) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)

  elif activity == "57":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)

  elif activity == "58":
    print("""
    (a) officiating
    (b) pitching
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)

  elif activity == "59":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((12*weight-1.375)*duration)
  elif activity == "60":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "61":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)

  elif activity == "62":
    print("""
    (a) singles
    (b) doubles
    (c) general
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)

  elif activity == "63":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.25)*duration)

  elif activity == "64":
    print("""
    (a) general
    (b) beach
    (c) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)

  elif activity == "65":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6*weight+0.4)*duration)
  elif activity == "66":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.95)*duration)
  elif activity == "67":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.95)*duration)

  elif activity == "68":
    print("""
    (a) ground level
    (b) upstairs
    (c) 7-10 kg, upstairs
    (d) 11-25 kg, upstairs
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight+0.25)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)

  elif activity == "69":
    print("""
    (a) standing, light
    (b) walk/run, moderate
    (c) walk/run, vigorous
    (d) carrying small children
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.8*weight-1.4)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)

  elif activity == "70":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)

  elif activity == "71":
    print("""
    (a) carrying up to 5 kg
    (b) carrying 5 to 10 kg
    (c) carrying 10 to 20 kg
    (d) carrying over 20 kg
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7.5*weight+1)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.15)*duration)


  elif activity == "72":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)
  elif activity == "73":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6.5*weight+0.45)*duration)
  elif activity == "74":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)
  elif activity == "75":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)
  elif activity == "76":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "77":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6.5*weight+0.45)*duration)
  elif activity == "78":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)


  elif activity == "79":
    print("""
    (a) under 1 m/s, very slow
    (b) 1 m/s, slow
    (c) walking the dog or walking downstairs 
    (d) 1 - 1.5 m/s, moderate
    (e) 1.5 m/s, brisk pace
    (f) walking using cructhes
    (g) 1.75 m/s, very brisk
    (h) 1.5 m/s, uphill
    (i) walking 2 m/s
    (j) walking 2.25 m/s
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:10]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2*weight+0.5)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.3*weight+0.4)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.8*weight-1.8)*duration)
    elif kind == "f":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration)
    elif kind == "g":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration)
    elif kind == "h":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "i":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6.3*weight+0.62)*duration)
    elif kind == "j":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)

  elif activity == "80":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((2.5*weight+0.64)*duration)

  elif activity == "81":
    print("""
    (a) rowing, light
    (b) camping trip
    (c) rowing, moderate
    (d) rowing, vigorous
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12*weight-1.375)*duration)

  elif activity == "82":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((12*weight-1.375)*duration)
  elif activity == "83":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)
  elif activity == "84":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "85":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)
  
  
  
  elif activity == "86":
    print("""
    (a) sailing, competition
    (b) sailing, yachting, ocean sailing
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration)

  elif activity == "87":
    print("""
    (a) water skiing
    (b) ski mobiling
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)  

  elif activity == "88":
    print("""
    (a) scuba diving
    (b) moderate
    (c) fast
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((12.5*weight+1.35)*duration)  
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((16*weight-0.64)*duration)  


  elif activity == "89":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)
  elif activity == "90":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)
  elif activity == "91":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)


  elif activity == "92":
    print("""
    (a) swimming laps, freestyle, slow
    (b) swimming laps, freestyle, fast
    (c) swimmng backstroke
    (d) swimming breaststroke
    (e) swimming butterfly
    (f) swimming leisurely, not laps
    (g) swimming sidestroke
    (h) swimming synchronized
    (i) swimming, treading water, moderate
    (j) swimming, treading water, fast, vigorous
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:10]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((11*weight-1)*duration)
    elif kind == "f":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)
    elif kind == "g":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "h":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)
    elif kind == "i":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)
    elif kind == "j":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((10*weight-0.62)*duration)

  elif activity == "93":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "94":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((10*weight-0.62)*duration)
  elif activity == "95":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)
  elif activity == "96":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)
  elif activity == "97":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3*weight+0.2)*duration)

  elif activity == "98":
    print("""
    (a) <4 m/s
    (b) average speed
    (c) rapidly
    (d) competitive
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5.5*weight+0.84)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration)  
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.15)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((15*weight-0.26)*duration)


  elif activity == "99":
    print("""
    (a) slow
    (b) moderate
    (c) vigorous
    (d) racing
    (e) uphill
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:5]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((7*weight+0.95)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)  
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((9*weight-1.15)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((14*weight-0.8)*duration)
    elif kind == "e":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((16.5*weight-0.16)*duration)

  elif activity == "100":
    print("""
    (a) light
    (b) moderate
    (c) racing
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5*weight+0.35)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((6*weight+0.4)*duration)  
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration)

  elif activity == "101":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((7*weight+0.95)*duration)
  elif activity == "102":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((8*weight-1.2)*duration)
  elif activity == "103":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3.5*weight+0.25)*duration)
  elif activity == "104":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3.5*weight+0.25)*duration)
  elif activity == "105":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((5*weight+0.35)*duration)
  elif activity == "106":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4.5*weight+0.75)*duration)

  elif activity == "107":
    print("""
    (a) sit
    (b) walk/run
    (c) bathing dog
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration)  
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.25)*duration)

  elif activity == "108":
    print("""
    (a) walk, power/mower
    (b) riding mower
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((5.5*weight+0.84)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration)  
    
  elif activity == "109":
    print("""
    (a) riding
    (b) walking
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration) 
    elif kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3.5*weight+0.25)*duration)  

  elif activity == "110":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((6*weight+0.4)*duration)
  elif activity == "111":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4.28*weight+1.4)*duration)

  elif activity == "112":
    print("""
    (a) general
    (b) bagging grass, leaves
    (c) watering lawn or garden
    (d) weeding, cultivating garden
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:4]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration) 
    if kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4*weight-0.18)*duration) 
    elif kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((1.5*weight+0.6)*duration)
    elif kind == "d":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((4.5*weight+0.75)*duration)

  elif activity == "113":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((3.5*weight+0.25)*duration)

  elif activity == "114":
    print("""
    (a) heavy loads
    (b) moderate loads upstairs
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:2]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration) 
    if kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((8*weight-1.2)*duration) 

  elif activity == "115":
    print("""
    (a) general
    (b) dusting
    (c) taking out trash
    """)
    kind = input("Choose the level of your activity ").lower()
    while kind not in list(string.ascii_lowercase)[:3]:
      print("Insert your level correctly")
      kind = input("Choose the level of your activity ").lower()
    if kind == "a":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.25)*duration) 
    if kind == "b":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((2.5*weight+0.64)*duration)
    if kind == "c":
      duration = float(input("""Duration (in hour) """))
      bmr_1 = int((3*weight+0.2)*duration) 

  elif activity == "116":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration)
  elif activity == "117":
    duration = float(input("""Duration (in hour) """))
    bmr_1 = int((4*weight-0.18)*duration) 
  while activity not in a:
    print("Insert your activity correctly")
    activity = input("Select your today activities ")

  return bmr_1

#User goal
def user_goal(name):
  user_goal = input("Choose your goal " + name + "\nGain/Maintain/Loss? ").lower()  
  while user_goal not in ["gain", "maintain", 'loss']:
    print("Please insert your goal correctly")
    user_goal = input("Choose your goal " + name + "\nGain/Maintain/Loss? ").lower()
  if user_goal == "gain":
    add_cal = int(500)
  elif user_goal == "maintain":
    add_cal = 0
  elif user_goal == "loss":
    add_cal = int(-500)
  return add_cal

#User age 
def user_age(name):
  age = int(input("What is your age " + name + " ? "))
  while age not in list(range(13, 61)):
    print("We need to say sorry, this app is only for 13 - 60 years old for now")
    age = int(input("What is your age " + name + " ? ")) 
  return age

#User height
def user_height(name):
  height = int(input("What is your height " + name + " "))
  while height not in list(range(80, 301)):
    print("Please insert your height correctly")
    height = int(input("What is your height " + name + " "))
  return height

#User weight
def user_weight(name):
  weight = int(input("What is your weight " + name + " "))
  while weight not in list(range(20, 500)):
    print("Please insert your weight correctly")
    weight = int(input("What is your weight " + name + " "))
  return weight

#Basal Metabolic Rate
def BMR(name, gender, height, weight, age, goal):
  if gender == "male":
    bmr = int(88.4 + (13.4*weight) + (4.8*height) - (5.68*age) + goal)
  elif gender == "female":
    bmr = int(447.6 + (9.25*weight) + (3.1*height) - (4.33*age) + goal)
  return bmr

def user_activity():
  activity_question = input("Do you have activity today? (Yes/No) ").lower()
  if activity_question == "no":
    aktivitas = 0
    return aktivitas
  elif activity_question == "yes":
    aktivitas = list_activity(weight)
    user_decision = input("""Do you want to add your activity ? (Yes/No) """).lower()
    while user_decision == "yes":
      aktivitas_2 = list_activity(weight)
      aktivitas = aktivitas + aktivitas_2
      user_decision = input("""Do you want to add your activity ? (Yes/No) """).lower()  
      while user_decision not in ['yes', 'no']:
        print("Answer it Yes or No")
        user_decision = input("""Do you want to add your activity ? (Yes/No) """).lower()    
      
      if user_decision == "no":
        return aktivitas
    if user_decision == "no":
      return aktivitas
    while user_decision not in ['yes', 'no']:
      print("Answer it Yes or No")
      user_decision = input("""Do you want to add your activity ? (Yes/No) """).lower()
  
  while activity not in ['yes', 'no']:
    print("Insert correctly")
    activity_question = input("Do you have activity today? (Yes/No)").lower()

def calories_need(bmr, user_activities):
  cal_need = bmr + user_activities
  return cal_need

state_1 = {
     0 : "Arsik",
     1 : "Ayam panggang bumbu kuning",
     2 : "Daging panggang",
     3 : "Ikan mas pepes",
     4 : "Sambal goreng tempe",
     5 : "Telur rebus",
     6 : "Telur dadar",
     7 : "Ati ayam goreng",
     8 : "Ayam pop",
     9 : "Bakso daging sapi",
     10 : "Empal daging",
     11 : "Ikan bandeng goreng",
     12 : "Ikan baronang goreng",
     13 : "Ikan bawal goreng",
     14 : "Ikan ekor goreng",
     15 : "Ikan kembung goreng",
     16 : "Ikan lele goreng",
     17 : "Ikan patin goreng",
     18 : "Ikan selar goreng",
     19 : "Ikan tenggiri goreng",
     20 : "Ikan teri goreng",
     21 : "Ikan tuna goreng",
     22 : "Tahu/tempe bacem",
     23 : "Telur mata sapi",
     24 : "Tahu/tempe goreng",
     25 : "Udang goreng",
     26 : "Sambal goreng tempe teri",
     27 : "Sambal goreng ati sapi",
     28 : "sambal goreng udang",
     29 : "Sop sapi",
 }

state_2 = {
     0 : "Acar kuning",
     1 : "Bayam",
     2 : "Cah labu siam",
     3 : "Sayur asam",
     4 : "Sop bayam",
     5 : "Sop mutiara jagung",
     6 : "Sop telur putih",
     7 : "Gudeg",
     8 : "Sayur lodeh",
     9 : "Cah jagung",
     10 : "Cah kacang panjang",
     11 : "Tumis buncis",
     12 : "Tumis daun singkong",
     13 : "Tumis kacang panjang + jagung",
     14 : "Sop Oyong"
 }
state_3 = {
     0 : "Apel",
     1 : "Belimbing",
     2 : "Jambu",
     3 : "Jeruk",
     4 : "Mangga",
     5 : "Nanas",
     6 : "Pepaya",
     7 : "Pir",
     8 : "Pisang",
     9 : "Salak",
     10 : "Semangka",
     11 : "Alpukat",
     12 : "Anggur",
     13 : "Lengkeng",
     14 : "Melon",
     15 : "Sirsak",
     16 : "Durian",
     17 : "Rambutan",
     18 : "Sawo",
     19 : "Jambu biji"
 }

prob_A = np.ones([len(state_1), len(state_1)], dtype = int)/len(state_1)
prob_B = np.ones([len(state_2), len(state_2)], dtype = int)/len(state_2)
prob_C = np.ones([len(state_3), len(state_3)], dtype = int)/len(state_3)

def saran(n,state,prob):
  start_state = 0
  curr_state = start_state
  a_list = []

  while len(a_list) < n:
    curr_state = np.random.choice(np.arange(len(state)), p=prob[curr_state])
    rec = state[curr_state]
    a_list.append(rec)
    start_state +=1
  return a_list

def maintain(n):
  A = saran(n, state_1, prob_A)
  B = saran(n, state_2, prob_B)
  C = saran(n, state_3, prob_C)
  D = np.array([A,B,C]).T.tolist()
  return {"foodLists": [
            {
                "breakfast": {
                    "food": D[0:3][0][0],
                    "vegetable": D[0:3][0][1],
                    "fruit": D[0:3][0][2]
                },
                "lunch": {
                    "food":D[0:3][1][0],
                    "vegetable":D[0:3][1][1],
                    "fruit":D[0:3][1][2]
                },
                "dinner": {
                    "food": D[0:3][2][0],
                    "vegetable": D[0:3][2][1],
                    "fruit": D[0:3][2][2]
                }
            },
            {
                "breakfast": {
                    "food": D[3:6][0][0],
                    "vegetable": D[3:6][0][1],
                    "fruit": D[3:6][0][2]
                },
                "lunch": {
                    "food": D[3:6][1][0],
                    "vegetable": D[3:6][1][1],
                    "fruit": D[3:6][1][2]
                },
                "dinner": {
                    "food": D[3:6][2][0],
                    "vegetable": D[3:6][2][1],
                    "fruit": D[3:6][2][2]
                }
            },
            {
                "breakfast": {
                    "food": D[6:9][0][0],
                    "vegetable": D[6:9][0][1],
                    "fruit": D[6:9][0][2]
                },
                "lunch": {
                    "food": D[6:9][1][0],
                    "vegetable": D[6:9][1][1],
                    "fruit": D[6:9][1][2]
                },
                "dinner": {
                    "food": D[6:9][2][0],
                    "vegetable": D[6:9][2][1],
                    "fruit": D[6:9][2][2]
                }
            }
        ]
        }

def loss(n):
  A = saran(n, state_1, prob_A)
  B = saran(n, state_2, prob_B)
  C = saran(n, state_3, prob_C)
  D = np.array([A,B,C]).T.tolist()

  return {"foodLists": [
            {
                "brunch": {
                    "food": D[0:2][0][0],
                    "vegetable": D[0:2][0][1],
                    "fruit": D[0:2][0][2]
                },
                "dinner": {
                    "food": D[0:2][1][0],
                    "vegetable": D[0:2][1][1],
                    "fruit": D[0:2][1][2]
                }
            },
            {
                "brunch": {
                    "food": D[2:4][0][0],
                    "vegetable": D[2:4][0][1],
                    "fruit": D[2:4][0][2]
                },
                "dinner": {
                    "food": D[2:4][1][0],
                    "vegetable": D[2:4][1][1],
                    "fruit": D[2:4][1][2]
                }
            },
            {
                "brunch": {
                    "food": D[4:6][0][0],
                    "vegetable": D[4:6][0][1],
                    "fruit": D[4:6][0][2]
                },
                "dinner": {
                    "food": D[4:6][1][0],
                    "vegetable": D[4:6][1][1],
                    "fruit": D[4:6][1][2]
                }
            }
        ]
        }

def gain(n):
  A = saran(n, state_1, prob_A)
  B = saran(n, state_2, prob_B)
  C = saran(n, state_3, prob_C)
  D = np.array([A,B,C]).T.tolist()
  return {"foodLists": [
            {
                "breakfast": {
                    "food": D[0:4][0][0],
                    "vegetable": D[0:4][0][1],
                    "fruit": D[0:4][0][2]
                },
                "brunch": {
                    "food":D[0:4][1][0],
                    "vegetable":D[0:4][1][1],
                    "fruit":D[0:4][1][2]
                },
                "lunch": {
                    "food":D[0:4][2][0],
                    "vegetable":D[0:4][2][1],
                    "fruit":D[0:4][2][2]
                },
                "dinner": {
                    "food": D[0:4][3][0],
                    "vegetable": D[0:4][3][1],
                    "fruit": D[0:4][3][2]
                }
            },
            {
                "breakfast": {
                    "food": D[4:8][0][0],
                    "vegetable": D[4:8][0][1],
                    "fruit": D[4:8][0][2]
                },
                "brunch": {
                    "food": D[4:8][1][0],
                    "vegetable": D[4:8][1][1],
                    "fruit": D[4:8][1][2]
                },
                "lunch": {
                    "food": D[4:8][2][0],
                    "vegetable": D[4:8][2][1],
                    "fruit": D[4:8][2][2]
                },
                "dinner": {
                    "food": D[4:8][3][0],
                    "vegetable": D[4:8][3][1],
                    "fruit": D[4:8][3][2]
                }
            },
            {
                "breakfast": {
                    "food": D[9:12][0][0],
                    "vegetable": D[9:12][0][1],
                    "fruit": D[9:12][0][2]
                },
                "brunch": {
                    "food": D[9:12][1][0],
                    "vegetable": D[9:12][1][1],
                    "fruit": D[9:12][1][2]
                },
                "lunch": {
                    "food": D[9:12][2][0],
                    "vegetable": D[9:12][2][1],
                    "fruit": D[9:12][2][2]
                },
                "dinner": {
                    "food": D[9:12][3][0],
                    "vegetable": D[9:12][3][1],
                    "fruit": D[9:12][3][2]
                }
            }
        ]
        }

name = user_name()
gender = user_gender(name)
goal = user_goal(name)
age = user_age(name)
height = user_height(name)
weight = user_weight(name)
bmr = BMR(name, gender, height, weight, age, goal)
user_activities = user_activity()
total = calories_need(bmr, user_activities)

if total > 1000 and total <= 2000:
  model = loss(6)
  str(model)
  output = {
    "totalCalories": total,
    "foodLists": model
  }
  print(output)
  # print("Calories: {} \n{}".format(total, model))
elif total > 2000 and total <= 3000:
  model = maintain(9)
  str(model)
  output = {
    "totalCalories": total,
    "foodLists": model
  }
  print(output)
  # print("Calories: {} \n{}".format(total, model))
elif total > 3000:
  model = gain(12)
  str(model)
  output = {
    "totalCalories": total,
    "foodLists": model
  }
  print(output)
  # print("Calories: {} \n{}".format(total, model))

